name: Build and Test

on:
  push:
    branches:
      - 'flatcap/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/neomutt/docker-build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Compilation Cache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Configure Neomutt
      run: ./configure --autocrypt --bdb --disable-idn --full-doc --gdbm --gnutls --gpgme --gss --idn2 --kyotocabinet --lmdb --lua --lz4 --notmuch --qdbm --sasl --tdb --tokyocabinet --with-lock=fcntl --zlib --zstd

    - name: Build Neomutt
      run: make -j 2

    - name: Neomutt Dump Screen
      shell: script -q -e -c "bash {0}"
      run: |
        export TERM=xterm-256color
        tty
        tput lines
        tput cols
        mkdir -p $HOME/Mail
        ./neomutt -d6 -l log -n -F dump.rc -f sample.mbox

    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: logs
        path: |
          log0
          dump0
        retention-days: 10

